### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by Xarfo** [Xarfo/Lambda-Notes-Backend#1]
## Trello Set Up

- [x] Use your existing Trello account from the Front End Project, or create a new one.
- [x] Create a new board called "Lambda Notes(Backend) - {Your Name}".
- [x] Create lists titled Backlog,To do, Blocked, In Progress, and Done.
- [x] Fill in the To do list with the MVP features listed below.
- [x] Fill in the backlog list with all the extra features listed below.
- [x] Share your board with the project manager that has been assigned to you. If you have not been assigned yet, reach out to       your Section Lead for guidance.
- [x] Add your Trello URL to your project's README.md file. Commit the change, push it to your repository & submit a pull request.

## Trello URL

[Abdul ahmad - Lambda Notes backend project Trello Board](https://trello.com/b/Zb9pjy39/lambda-notesbackend-abdul-ahmad)

## Backend MVP Features:

We recommend that you finish all the MVP features before trying to deploy.

- [x] Add data persistence using a Relational Database. We suggest you start with SQLite3.
- [x] Create a Web API for the React application you built in the front-end project week.
- [x] Build endpoints for each of the following features:
          - Display a list of notes.
          - Create a note with a title and content.
          - View an existing note.
          - Edit an existing note.
          - Delete an existing note.
          - Modify your front-end so that it uses your newly created Web API.
